--- 
title: "Gradient-enhanced Gaussian Process Regression"
author: "Pascal Pernot"
date: '`r Sys.Date()`'
output:
  html_document:
    highlight: tango
    number_sections: yes
    theme: cerulean
    toc: yes
---

```{r setup, include=FALSE}
rm(list = ls()); gc() # Clean environment

libs =c('rstan','knitr')
for (lib in libs ) {
  if(!require(lib,character.only = TRUE))
    install.packages(lib,dependencies=TRUE)
 library(lib,character.only = TRUE)
}
rstan_options(auto_write = TRUE)

set.seed(1234) # Initialise la graine du RNG

# Couleurs transparente
blue_tr  = rgb(0.1,0.1,0.9,alpha=0.1) 

plot_predict <- function(data,fit,probs=c(0.025,0.5,0.975),cex=1) {
  # Plot prediction intervals 
  
  y_pred = extract(fit,"y2")[[1]]
  q_pred = matrix(NA,ncol=length(probs),nrow=length(data$x2))
  for (i in 1:length(data$x2)) {
    q_pred[i,] = quantile(y_pred[,i],probs=probs)
  }
  
  par(mar=c(3,3,1.6,.2),mgp=c(2,.75,0), 
      pty='s',tcl=-0.5, cex=cex)
  matplot(data$x2, data$x2, type='n',ylim=range(data$y1), 
          xlab='x', ylab='y')
  grid(); box()
  polygon(cbind(data$x2,rev(data$x2)),
          cbind(q_pred[,1],rev(q_pred[,3])),
          col=blue_tr, border=NA)
  lines(data$x2,q_pred[,2],lwd=2,col=4,lty=2)
  points(data$x1,data$y1,type='p',pch=19,col=2,cex=0.5)
  segments(data$x1,data$y1-2*data$uy1,data$x1,data$y1+2*data$uy1,
           lwd=2,col=2)
}
```

# Use of gradients in GP

## Synthetic data

```{r robData, echo=FALSE, message=FALSE, warning=FALSE}

fmod = expression(sin(x))
# fmod = expression((x-2)^2)

# Generate data
N1 = 6
sd = 0.02
x_min = 1; x_max = 10
x1 = seq(from = x_min, to = x_max, length.out = N1)
y1 = eval(fmod,list(x=x1))  + sd*rnorm(N1)
uy1= rep(sd,length(x1))
dy1 = as.vector(attr(eval(deriv(fmod,"x"),list(x=x1)),"gradient")) +
  sd*rnorm(N1)
udy1= rep(sd,length(x1))

# Prediction grid
N2 = 50
x2 = seq(-1,11,length.out = N2)

# Plot data points and gradients
plot(x1,y1,pch=19,col=2,cex=0.5)
lines(x2,eval(fmod,list(x=x2)),col=2,lty=3)
segments(x1,y1-2*uy1,x1,y1+2*uy1,lwd=2,col=2)
segments(x1-0.1,y1-0.1*dy1,x1+0.1,y1+0.1*dy1,lwd=2,col=3)

# Save data
stan_rdump(c("N1", "x1","y1","uy1","dy1","udy1","N2","x2"), file="mydata.R")

```

## Standard GP

```{r GP}
mod = stan_model(file = 'GP.stan')

input_data <- read_rdump("mydata.R")
fit = sampling(mod, data = input_data,
               iter = 2000, chains = 1, warmup = 1000)

pars = c("eta_sq", "inv_rho_sq")
ab_summary <- summary(fit, pars = pars, 
                      probs = c(0.025, 0.975))$summary
knitr::kable(ab_summary[,c('mean','sd','2.5%','97.5%','n_eff','Rhat')],digits=3)

traceplot(fit,pars=pars,inc_warmup=TRUE)
pairs(fit,pars=pars)

plot_predict(input_data,fit)
lines(x2,eval(fmod,list(x=x2)),col=2,lty=3)
title(main='Standard GP')
```


## Gradient-Enhanced GP

```{r GEGP}
modGE = stan_model(file = 'GEGP0.stan')

input_data <- read_rdump("mydata.R")

fitGE = sampling(modGE, data = input_data,
                 iter = 2000, chains = 1, warmup = 1000)

pars = c("eta_sq", "inv_rho_sq")
ab_summary <- summary(fitGE, pars = pars, 
                      probs = c(0.025, 0.975))$summary
knitr::kable(ab_summary[,c('mean','sd','2.5%','97.5%','n_eff','Rhat')],digits=3)

traceplot(fitGE,pars=pars,inc_warmup=TRUE)
pairs(fitGE,pars=pars)

plot_predict(input_data,fitGE) 
lines(x2,eval(fmod,list(x=x2)),col=2,lty=3)
segments(x1-0.1,y1-0.1*dy1,x1+0.1,y1+0.1*dy1,lwd=2,col=3)
title(main='Gradient-enhanced GP')
```


## Comparison

```{r compare, echo=FALSE, message=FALSE, warning=FALSE}
par(mfrow = c(1,2))

plot_predict(input_data,fit)
lines(x2,eval(fmod,list(x=x2)),col=2,lty=3)
title(main='Standard GP')

plot_predict(input_data,fitGE) 
lines(x2,eval(fmod,list(x=x2)),col=2,lty=3)
segments(x1-0.1,y1-0.1*dy1,x1+0.1,y1+0.1*dy1,lwd=2,col=3)
title(main='Gradient-enhanced GP')

```
