--- 
title: "2D Gradient-enhanced Gaussian Process Regression"
subtitle: "Separate calibration from prediction..."
author: "Pascal Pernot"
date: '`r Sys.Date()`'
output:
  html_document:
    highlight: tango
    number_sections: yes
    theme: cerulean
    toc: yes
---

```{r setup, include=FALSE}
rm(list = ls()); gc() # Clean environment

libs =c('rstan','knitr','DiceKriging','numDeriv','lhs')
for (lib in libs ) {
  if(!require(lib,character.only = TRUE))
    install.packages(lib,dependencies=TRUE)
 library(lib,character.only = TRUE)
}
rstan_options(auto_write = TRUE)

set.seed(1234) # Initialise la graine du RNG

# Couleurs transparente
blue_tr  = rgb(0.1,0.1,0.9,alpha=0.3) 

plot_predict2D <- function(data,fit,probs=c(0.025,0.5,0.975),cex=1) {
  
  y_pred = extract(fit,"y2")[[1]]
  q_pred = matrix(NA,ncol=length(probs),nrow=data$N2)
  for (i in 1:data$N2) {
    q_pred[i,] = quantile(y_pred[,i],probs=probs)
  }

  par(mar=c(3,3,1.6,.2),mgp=c(2,.75,0), 
      pty='s',tcl=-0.5, cex=cex)
  contour(sort(unique(data$x2[,1])), 
          sort(unique(data$x2[,2])), 
          matrix(q_pred[,2], 10, 10), 
          50, col=3, main="Median")
}
checkPredict <- function(input,model,probs=c(0.025,0.5,0.975)) {
  
  # Check predicted values at calibration points
  input_check = input
  input_check$N2 = input$N1
  input_check$x2 = input$x1
  input_check$y2 = input$y1
  fitCheck = sampling(model, data = input_check,
                 iter = 2000, chains = 1, warmup = 1000)
  y_p = extract(fitCheck,"y2")[[1]]
  
  q_p = matrix(NA,ncol=length(probs),nrow=input_check$N2)
  for (i in 1:input_check$N2) {
    q_p[i,] = quantile(y_p[,i],probs=probs)
  }
  y_m  = apply(y_p,2,mean)
  
  x1  = input$x1
  y1  = input$y1
  uy1 = input$uy1
  par(mfrow=c(1,ncol(x1)))
  for(idim in 1:ncol(x1)) {
    plot(x1[,idim],y1,ylim=range(q_p),main=paste('Dimension:',idim))
    grid();box()
    segments(x1[,idim],y1-2*uy1,x1[,idim],y1+2*uy1,lwd=8,col=3)
    segments(x1[,idim],q_p[,1],x1[,idim],q_p[,3],lwd=4,col='orange')
    legend('topright',legend=c('Data','Pred.'),col=c(3,'orange'),lwd=c(8,4))
  }
  
}
```

# Synthetic data

```{r robData, echo=FALSE, message=FALSE, warning=FALSE}

branin = function (x) {
    x1 <- x[1] - 0.5
    x2 <- x[2] - 0.5
    x1^4 + x2^2 + x1*x2
    # sum(x)
}

M=2 # Ndim

x1 = lhs::randomLHS(10,M)
N1 = nrow(x1)
y1 = apply(x1, 1, branin) 
uy1 = abs(y1 *0.010)
y1 = y1 + rnorm(N1,0,uy1)

dy1 = udy1 = matrix(N1,nrow=N1,ncol=M)
for (i in 1:N1)
  dy1[i,1:M] = numDeriv::grad(branin, t(x1[i,1:M]))

udy1 = abs(dy1*0.010)
dy1 = dy1 + matrix(rnorm(N1*M,0,udy1),ncol=M)


# Prediction grid
n2 = 10
t1 = t2 = seq(0,1,length=n2)
x2 = expand.grid(x1=t1, x2=t2)
y2_ref = apply(x2, 1, branin) 
N2 = nrow(x2)

# Save data
stan_rdump(c("M","N1", "x1","y1","uy1","dy1","udy1","N2","x2"), 
           file="mydata2D.R")

# Plot data points and gradients
par(mfrow=c(1,1))
par(mar=c(3,3,1.6,.2),mgp=c(2,.75,0), 
    pty='s',tcl=-0.5, cex=1)
contour(t1, t2, matrix(y2_ref, n2, n2), 20, col='brown', 
        ylim=c(0,1.2))
box();grid()
points(x1[,1], x1[,2], pch=19, cex=1.0, col=2)
points(x2[,1], x2[,2], pch=17, cex=0.5, col=3)
legend('topleft',
       legend = c('Calib. pt.','Pred. pt.'),
       col = c(2,3), pch=c(19,17), cex=1,
       ncol=2, bg = 'gray90', box.col='gray90')
dx =0.025
for (i in 1:1000) {
  g1 = dy1[,1] + rnorm(N1,0,udy1[,1])
  g2 = dy1[,2] + rnorm(N1,0,udy1[,2])
  segments(x1[,1],    x1[,2], 
           x1[,1]+dx, x1[,2]-dx*g1/g2,
           col=blue_tr,lwd=1)
  segments(x1[,1],    x1[,2], 
           x1[,1]-dx, x1[,2]+dx*g1/g2,
           col=blue_tr,lwd=1)
}

par(mfrow=c(1,3))
plot(x1[,2],y1)
segments(x1[,2],y1-2*uy1,x1[,2],y1+2*uy1)
plot(x1[,2],dy1[,1])
segments(x1[,2],dy1[,1]-2*udy1[,1],x1[,2],dy1[,1]+2*udy1[,1])
plot(x1[,2],dy1[,2])
segments(x1[,2],dy1[,2]-2*udy1[,2],x1[,2],dy1[,2]+2*udy1[,2])

```

# Standard GP

```{r GP}
input_data <- read_rdump("mydata2D.R")
input_data$use_gradients = 0

# Bayes GP
modCal = stan_model(file = 'GEGPNDCal.stan')
fit = sampling(modCal, data = input_data,
               iter = 4000, chains = 1, warmup = 3000)

pars = c("eta_sq", "corlen")
ab_summary <- summary(fit, pars = pars, 
                      probs = c(0.025, 0.975))$summary
knitr::kable(ab_summary[,c('mean','sd','2.5%','97.5%','n_eff','Rhat')],digits=3)

rstan::traceplot(fit,pars=pars,inc_warmup=FALSE)
pairs(fit,pars=pars)

modPred = stan_model(file = 'GEGPNDPred.stan')
imap = which.max(extract(fit)$lp_)
input_data$eta_sq = extract(fit)$eta_sq[imap]
input_data$corlen = extract(fit)$corlen[imap,]

fitp = sampling(modPred, data = input_data,
               iter = 2000, chains = 1, warmup = 1000)

probs=c(0.025,0.5,0.975)
y_p = extract(fitp,"y2")[[1]]
q_pred = matrix(NA,ncol=length(probs),nrow=input_data$N2)
for (i in 1:input_data$N2) {
  q_pred[i,] = quantile(y_p[,i],probs=probs)
}
y_pred = apply(y_p,2,mean)
uy_pred = q_pred[,3]-q_pred[,1]
  
# DiceKriging
m1 <- km(design=input_data$x1,
         response=input_data$y1,
         noise.var=input_data$uy1^2,
         covtype="gauss",
         coef.trend = mean(input_data$y1) )
covparam2vect(m1@covariance)
m1@covariance@sd2
m1@trend.coef
dice_pred = predict(m1, input_data$x2, "UK")
y_pred_m1  <- dice_pred$mean
y_pred_m1l <- dice_pred$lower95
y_pred_m1u <- dice_pred$upper95


#Compare

(rmsd = sqrt(sum((y2_ref-y_pred)^2/y2_ref^2)))
(rmsd1 = sqrt(sum((y2_ref-y_pred_m1)^2/y2_ref^2)))


xlim=range(y2_ref)
par(mfrow=c(1,2))
par(mar=c(3,3,1.6,.2),mgp=c(2,.75,0),
    pty='s',tcl=-0.5, cex=1)
plot(y_pred,y2_ref,pch=19,col=blue_tr, xlim=xlim, ylim=xlim,
     main=paste0('GP: Ref = ',nrow(input_data$x1),' points'))
segments(q_pred[,1],y2_ref,q_pred[,3],y2_ref,col=blue_tr,lwd=2)
abline(a=0,b=1,col=2);grid();box()

par(mar=c(3,3,1.6,.2),mgp=c(2,.75,0),
    pty='s',tcl=-0.5, cex=1)
plot(y_pred_m1,y2_ref,pch=19,col=blue_tr, xlim=xlim, ylim=xlim,
     main=paste0('Dice: Ref = ',nrow(input_data$x1),' points'))
segments(y_pred_m1l,y2_ref,y_pred_m1u,y2_ref,col=blue_tr,lwd=2)
abline(a=0,b=1,col=2);grid();box()

# Plot data points and gradients
par(mfrow=c(1,2),
    mar=c(3,3,1.6,.2),mgp=c(2,.75,0), 
    pty='s',tcl=-0.5, cex=1)
contour(t1, t2, matrix(y_pred, n2, n2), 20, col=4, main="Mean",
     xlab=expression(x[1]),ylab=expression(x[2]))
grid();box()
points(x1[,1], x1[,2], pch=19, cex=1.0, col=2)
legend('topleft',
       legend = c('Calib. pt.','Pred. pt.'),
       col = c(2,3), pch=c(19,17), cex=1.0,
       ncol=2, bg = 'gray90', box.col='gray90')
text(x1[,1], x1[,2], 1:nrow(x1), cex=1.0, col=1)

contour(t1, t2, matrix(uy_pred, n2, n2), 20, col=4, main="Q95",
        # zlim = c(0,1),
        xlab=expression(x[1]),ylab=expression(x[2]))
grid();box()
points(x1[,1], x1[,2], pch=19, cex=1.0, col=2)
# points(x2[,1], x2[,2], pch=17, cex=1.0, col=3)

# Check values at calibration points
checkPredict(input=input_data, model=modPred)

```


# Gradient-Enhanced GP

```{r GEGP}
input_data <- read_rdump("mydata2D.R")
input_data$use_gradients = 1

fitGE = sampling(modCal, data = input_data,
                 iter = 4000, chains = 1, warmup = 3000)

ab_summary <- summary(fitGE, pars = pars, 
                      probs = c(0.025, 0.975))$summary
knitr::kable(ab_summary[,c('mean','sd','2.5%','97.5%','n_eff','Rhat')],digits=3)

rstan::traceplot(fitGE,pars=pars,inc_warmup=FALSE)
pairs(fitGE,pars=pars,gap=0)


imap = which.max(extract(fitGE)$lp_)
input_data$eta_sq = extract(fitGE)$eta_sq[imap]
input_data$corlen = extract(fitGE)$corlen[imap,]

fitGEp = sampling(modPred, data = input_data,
               iter = 2000, chains = 1, warmup = 1000)

probs=c(0.025,0.5,0.975)
y_p = extract(fitGEp,"y2")[[1]]
q_pred = matrix(NA,ncol=length(probs),nrow=input_data$N2)
for (i in 1:input_data$N2) {
  q_pred[i,] = quantile(y_p[,i],probs=probs)
}
y_predG = apply(y_p,2,mean)
uy_predG = q_pred[,3]-q_pred[,1]

(rmsd = sqrt(sum((y2_ref-y_pred)^2/y2_ref^2)))
(rmsd1 = sqrt(sum((y2_ref-y_pred_m1)^2/y2_ref^2)))

xlim=range(y2_ref)
par(mfrow=c(1,2))
par(mar=c(3,3,1.6,.2),mgp=c(2,.75,0),
    pty='s',tcl=-0.5, cex=1)
plot(y_predG,y2_ref,pch=19,col=blue_tr, xlim=xlim, ylim=xlim,
     main=paste0('GEGP: Ref = ',nrow(input_data$x1),' points'))
segments(q_pred[,1],y2_ref,q_pred[,3],y2_ref,col=blue_tr,lwd=2)
abline(a=0,b=1,col=2);grid();box()


par(mar=c(3,3,1.6,.2),mgp=c(2,.75,0),
    pty='s',tcl=-0.5, cex=1)
plot(y_pred_m1,y2_ref,pch=19,col=blue_tr, xlim=xlim, ylim=xlim,
     main=paste0('Dice: Ref = ',nrow(input_data$x1),' points'))
segments(y_pred_m1l,y2_ref,y_pred_m1u,y2_ref,col=blue_tr,lwd=2)
abline(a=0,b=1,col=2);grid();box()

# Plot data points and gradients
par(mfrow=c(1,2),
    mar=c(3,3,1.6,.2),mgp=c(2,.75,0), 
    pty='s',tcl=-0.5, cex=1)
contour(t1, t2, matrix(y_predG, n2, n2), 20, col=4, main="Mean",
        xlab=expression(x[1]),ylab=expression(x[2]))
grid();box()
points(x1[,1], x1[,2], pch=19, cex=1.0, col=2)
dx =0.025
segments(x1[,1],    x1[,2],
         x1[,1]+dx, x1[,2]-dx*dy1[,1]/dy1[,2],
         col=2)
segments(x1[,1],    x1[,2],
         x1[,1]-dx, x1[,2]+dx*dy1[,1]/dy1[,2],
         col=2)
legend('topleft',
       legend = c('Calib. pt.','Pred. pt.'),
       col = c(2,3), pch=c(19,17), cex=1.0,
       ncol=2, bg = 'gray90', box.col='gray90')
text(x1[,1], x1[,2], 1:nrow(x1), cex=1.0, col=1)

contour(t1, t2, matrix(uy_predG, n2, n2), 20, col=4, main="Q95",
        # zlim = c(0,1),
        xlab=expression(x[1]),ylab=expression(x[2]))
grid();box()
points(x1[,1], x1[,2], pch=19, cex=1.0, col=2)
# points(x2[,1], x2[,2], pch=17, cex=1.0, col=3)

# Check values at calibration points
checkPredict(input=input_data, model=modPred)

```

```{r compare}

par(mfrow=c(1,3),
    mar=c(3,3,1.6,.2),mgp=c(2,.75,0), 
    pty='s',tcl=-0.5, cex=1)
contour(t1, t2, matrix(y2_ref, n2, n2), 20, col=4, main="Ref",
        xlab=expression(x[1]),ylab=expression(x[2]))
grid();box()

contour(t1, t2, matrix(y_pred, n2, n2), 20, col=4, main="GP",
        xlab=expression(x[1]),ylab=expression(x[2]))
grid();box()
points(x1[,1], x1[,2], pch=19, cex=1.0, col=2)

contour(t1, t2, matrix(y_predG, n2, n2), 20, col=4, main="GEGP",
        xlab=expression(x[1]),ylab=expression(x[2]))
grid();box()
points(x1[,1], x1[,2], pch=19, cex=1.0, col=2)

par(mfrow=c(1,2))
par(mar=c(3,3,1.6,.2),mgp=c(2,.75,0),
    pty='s',tcl=-0.5, cex=1)

plot(y_pred,y2_ref,pch=19,col=blue_tr, xlim=xlim, ylim=xlim,
     main=paste0('GP: Ref = ',nrow(input_data$x1),' points'))
# segments(q_pred[,1],y2_ref,q_pred[,3],y2_ref,col=blue_tr,lwd=2)
abline(a=0,b=1,col=2);grid();box()

plot(y_predG,y2_ref,pch=19,col=blue_tr, xlim=xlim, ylim=xlim,
     main=paste0('GEGP: Ref = ',nrow(input_data$x1),' points'))
# segments(q_pred[,1],y2_ref,q_pred[,3],y2_ref,col=blue_tr,lwd=2)
abline(a=0,b=1,col=2);grid();box()

```

